### ISSUE TITLE
Available configuration params are not clear

### ISSUE THREAD

**Issue by zenkay** [singer-io/tap-s3-csv#14]
Hi everybody,

I'm new to Singer and I'm trying to use this tap but I'm not able to understand which are the available config params and how should I use them. 

Colud you please add a few details to the README?
Or simply give me an example configuration, I'd be happy to open a PR with updated README for you!

Thanks

**Comment by dmosorast** [comment]
Hi @zenkay, yes, the parameters involved in this tap are pretty confusing, and had been evolving for quite awhile, so the README description is a bit of an oversight. Here is a basic config, and a bit of a run down on each of the properties:

```
{
    "start_date": "2017-11-02T00:00:00Z",
    "account_id": "1234567890",
    "role_name": "role_with_bucket_access",
    "bucket": "my-bucket",
    "external_id": "my_optional_secret_external_id",
    "tables": "[{\"search_prefix\":\"exports\",\"search_pattern\":\"my_table\\\\/.*\\\\.csv\",\"table_name\":\"my_table\",\"key_properties\":\"id\",\"date_overrides\":\"created_at\",\"delimiter\":\",\"}]",
}
```

**start_date** - Pretty straightforward, this is the datetime that the tap will use to look for newly updated or created files, based on the modified timestamp on the file.
**account_id** - This is your AWS account id
**role_name** - In order to access a bucket, the tap uses `boto3` to log in as a role in your AWS account. If you have your AWS account credentials, you can specify this as a role which your local user has access to assume, `boto3` should by default pick up your AWS keys from the local environment.
**bucket** - The name of the bucket to search to files under.
**external_id** - (potentially optional) Running this locally, you should be able to omit this property, it is provided to allow the tap to access buckets in accounts where the user doesn't have access to the account itself, but is able to assume a role in that account, through a shared secret. This is that secret, in that case.
**tables** - This one is a bit tough to craft, and I'll explain more below, but generally. This is an *escaped JSON string* that the tap will use to search for files, and emit records as "tables" from those files.

Here is a bit more about the table spec, from the example above. You can find the `voluptuous` spec used to verify this [here](https://github.com/singer-io/tap-s3-csv/blob/master/tap_s3_csv/config.py):

```
[
    {
        "search_prefix": "exports"
        "search_pattern": "my_table\\/.*\\.csv",
        "table_name": "my_table",
        "key_properties": "id",
        "date_overrides": "created_at",
        "delimiter": ","
    },
    ...
]
```

**search_prefix** - This is a prefix to apply after the bucket, but before the file search pattern, to allow you to find files in "directories" below the bucket.
**search_pattern** - This is an escaped regular expression that the tap will use to find files in the bucket + prefix. It's a bit strange, since this is an escaped string inside of an escaped string, any backslashes in the RegEx will need to be double-escaped.
**table_name** - This is an arbitrary value, and will be used to name the stream that records are emitted under for files matching bucket + prefix + pattern.
**key_properties** - These are the "primary keys" of the CSV files, to be used by the target however it makes sense.
**date_overrides** - Specifies field names in the files that are supposed to be parsed as a datetime. The tap doesn't attempt to automatically determine if a field is a datetime, so this will make it explicit in the discovered schema.
**delimiter** - This allows you to specify a custom delimiter, such as `\t` or `|`, if that applies to your files.

Hope this is helpful! Feel free to clean it up and add anything I missed to the README in a PR.

**Comment by zenkay** [comment]
Hi @dmosorast,

apologize for the delayed response. I'm working on this stuff only from times to time and I completely forgot to thank you for the answer.

I opened the PR for the README a few minutes ago.
Thank you again

**Comment by dmosorast** [comment]
@zenkay No problem! A lot of our contributors are only able to hop on every so often. I'll take a look at that PR. Thanks!
